runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: favicon\.ico
- url: /i
  static_dir: static
- url: .*
  script: main.app
